### PR TITLE
Open pull to check linterns

### PR DESCRIPTION
**Pull request by kitpao**

### CODE REVIEW

**Comment by kitpao** [comment]
Hello, my project is finished, could you check it please? :)

**Review by stratospherique — COMMENTED** [review]
### Pull request under review by Ahmed Mahfoudh TSE

**Review by stratospherique — APPROVED** [review]
### Great work @kitpao :clap: :clap: . Your project satisfies all the necessary requirements :100: . Your project is approved and you can merge to master :+1: :+1: .

**Comment by kitpao** [comment]
thank you!

**Pull request merged**
